### ISSUE TITLE
Simplify the language

### ISSUE THREAD

**Issue by henno** [tupleapp/pair-programming-guide#12]
As a developer who wants to use The Case for Pair Programming article to "sell" pair programming idea to whomever he needs to also convince that pair programming is the way to go, I want this article to be easy to understand for people with limited technical background and English as not their first language.

What this means is that in order to appeal to these people too, the article needs to substitute fancy technical terms with simple language or add "in other words ..." to explain what is said to non-technical people.

The people I have in mind are the ones who have the wallet but are not (yet) convinced that in the long term two persons doing the same thing together is more efficient than them doing different things in parallel.

**Comment by r00k** [comment]
Hey! Thanks for opening this issue.

I'm going to close this for now since it's very general and hard to act on.

If you'd like to reopen an issue with specific sentences that you think others will find hard to understand, I'll consider editing them.
