### ISSUE TITLE
Can't communicate after installing zoom

### ISSUE THREAD

**Issue by luke-mahony** [tupleapp/pair-programming-guide#18]
Our team has been using Tuple for pairing for the past few weeks and all was going well until we all installed zoom for a client meeting today. We can still connect to each other but we can't hear each other speak or share screens. We've gone through some basic trouble shooting, checking accessibility permissions, closing the app and reopening, uninstalling zoom entirely and trying to reopen Tuple again and restarting our machines. Im not sure if us installing zoom is related to the issue but it seems to have happened to all of simultaneously shortly after install. If you have any information on why this might be happening and how we might be able to fix the issue it would be appreciated.

**Comment by robamaton** [comment]
There was an issue with Twilio (which we use for Network Traversal) earlier today which appears to be resolved: https://status.twilio.com/incidents/fyszvy4t4kgw. Can you verify if you are still unable to establish calls, and confirm the timeframe you were experiencing issues? If it's still a problem I'd like to reach out to Twilio. Thanks!

**Comment by robamaton** [comment]
Based on other user feedback, looks like this is resolved.
