### ISSUE TITLE
Lesser-Known Benefit: You’ll Share Knowledge

### ISSUE THREAD

**Issue by hugo** [tupleapp/pair-programming-guide#2]
A healthy team will find time to spread knowledge. A team that pairs will do it as a matter of course.

This could be as trivial as a helpful editor shortcut, or a neat language feature. Occasionally it’s as profound as a totally new perspective about software.

**Comment by r00k** [comment]
Thanks for the idea!

While I totally agree that this is a wonderful benefit to pairing, I actually see it mentioned fairly frequently by folks making the case.
