### ISSUE TITLE
Lesser-Known Benefit: You’ll Default to Collaboration

### ISSUE THREAD

**Issue by hugo** [tupleapp/pair-programming-guide#3]
Pairing trains you to view coding as a team sport, even when not actively pairing. When faced with a difficult task, you’ll solicit feedback on the best approach, before diving in. When you hit a roadblock, you’ll reach out for help, not bang your head against the problem. When it’s time to do code review, you’ll talk through the author’s work with them, not drive-by nit-pick their coding style.

- - -

I haven’t personally heard this talked about (but with your better knowledge and experience you might have). 

P.S. I hope you don’t mind me submitting these as I think of them; I’d rather suggest a bad idea than not suggest a good one.

**Comment by SpencerCDixon** [comment]
These are awesome!  Thanks for the submission @hugo keep them coming

**Comment by r00k** [comment]
> P.S. I hope you don’t mind me submitting these as I think of them; I’d rather suggest a bad idea than not suggest a good one.

Definitely do not mind! Please keep it up.
