### ISSUE TITLE
Comparing unequal resources in Pairing vs. Individual coding topics

### ISSUE THREAD

**Issue by tkbrigham** [tupleapp/pair-programming-guide#6]
I love that you all have a [Scientific Research](https://tuple.app/pair-programming-guide/scientific-research-into-pair-programming) section. As you say - it's hard to find data on this.

One large gap for me was transparency and discussion around the fact that **pairing takes 2x developers**. I think there should be some acknowledgement of that massive factor, and that seems to be opaque or skipped over. 

Example of a hint at this topic, **emphasis** mine:
> Wiliams, L. A. (2000)
> 
> An experiment was run in 1999 with approximately 40 senior Computer Science students at the University of Utah. **Two-thirds** of the students worked in two-person collaborative teams […]. **The other students** worked independently […] to develop the same assignments. The productivity, cycle time, and quality of the two groups have been compared. Empirical results point in favor of the collaborative teams […].

This implies that there were twice and many resources devoted to pairing. Perhaps a good relevant discussion would contrast pairing and individual coding with a fixed number of developers doing each, and compare the output in those cases.

Small disclaimer that I thoroughly enjoy pairing, and I love the robustness of this site. I think this is a glaring issue that presents something of an Achilles heel to the validity of these arguments if not addressed.

**Comment by r00k** [comment]
I'm having trouble determining this for sure, but I _think_ this is taken into consideration when examining the results:

> Many people’s gut reaction is to reject the idea of pair programming because they assume that there will be a 100% programmer-hour increase by putting two programmers on a job that one can do. After the initial adjustment period, discussed above, the **total programmer hours** spent on each assignment trended downward dramatically as shown below and reported in [10]. By program 4 in the formal experiment, the difference between the times for individuals and for the pairs was no longer statistically significant.

My reading of that section is that they are considering total hours (where the pair's hours are doubled) rather than naively comparing a pair vs an individual.

Indeed, if they _didn't_ do that, I think that'd be pretty shoddy research.

If you can find anything that clarifies that point, I'd be interested to see it :)
